{
  "artifacts": [],
  "command": "my_main",
  "experiment": {
    "base_dir": "C:\\Users\\Utente\\Desktop\\SC2Tesy\\src",
    "dependencies": [
      "munch==2.3.2",
      "numpy==1.15.2",
      "sacred==0.7.5",
      "torch==1.2.0+cpu"
    ],
    "mainfile": "main.py",
    "name": "pymarl",
    "repositories": [],
    "sources": [
      [
        "main.py",
        "_sources\\main_9b5c59c853d96c46f9ec2eb002cb3559.py"
      ],
      [
        "run.py",
        "_sources\\run_3d041e9dfb93478d76bc56d4c3315843.py"
      ],
      [
        "utils\\logging.py",
        "_sources\\logging_aa14e56e60b01dd7a9ddb8e6cdf36b85.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\Utente\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\sacred\\config\\captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"C:/Users/Utente/Desktop/SC2Tesy/src/main.py\", line 34, in my_main\n    run(_run, _config, _log)\n",
    "  File \"C:\\Users\\Utente\\Desktop\\SC2Tesy\\src\\run.py\", line 49, in run\n    run_sequential(args=args, logger=logger)\n",
    "  File \"C:\\Users\\Utente\\Desktop\\SC2Tesy\\src\\run.py\", line 180, in run_sequential\n    learner.train(episode_sample, runner.t_env, episode)\n",
    "  File \"C:\\Users\\Utente\\Desktop\\SC2Tesy\\src\\learners\\q_learner.py\", line 100, in train\n    loss.backward()\n",
    "  File \"C:\\Users\\Utente\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\torch\\tensor.py\", line 118, in backward\n    torch.autograd.backward(self, gradient, retain_graph, create_graph)\n",
    "  File \"C:\\Users\\Utente\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\torch\\autograd\\__init__.py\", line 93, in backward\n    allow_unreachable=True)  # allow_unreachable flag\n",
    "RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [32, 79, 5, 11]], which is output 0 of SliceBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).\n"
  ],
  "heartbeat": "2019-09-21T10:51:44.803787",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz",
    "hostname": "DESKTOP-MRAC360",
    "os": [
      "Windows",
      "Windows-10-10.0.18362-SP0"
    ],
    "python_version": "3.6.8"
  },
  "meta": {
    "command": "my_main",
    "options": {
      "--beat_interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print_config": false,
      "--priority": null,
      "--queue": false,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [
        "env_args.map_name=2s3z"
      ],
      "help": false,
      "with": true
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2019-09-21T10:43:52.088977",
  "status": "FAILED",
  "stop_time": "2019-09-21T10:51:44.927518"
}